---
- name: Create local user on managed host
  hosts: serverb
  tasks:
    - name: Add krishna user on serverb
      ansible.builtin.user:
        name: krishna
        comment: 'Sys Admin'
        state: present
